### PR TITLE
Specify UTF-8 encoding when reading TOML files.

### PR DESCRIPTION
**Pull request by domdfcoding**
This avoids a ``UnicodeDecodeError`` when reading ``pyproject.toml`` files containing unicode characters on Windows. These characters may be present in a project's metadata, such as its description or an author's name.

Furthermore, the [TOML specification](https://toml.io/en/v1.0.0#spec) requires files to be encoded in UTF-8.

### CODE REVIEW

**Comment by domdfcoding** [comment]
I can't directly test this on Windows because of https://github.com/xolox/python-humanfriendly/issues/44, but the issue I was seeing goes away when using my branch.

**Comment by domdfcoding** [comment]
I have had a go at making the test suite pass on Windows [in my fork](https://github.com/domdfcoding/check-wheel-contents/tree/windows).

**Comment by jwodder** [comment]
@domdfcoding Thank you very much!  This PR looks fine to me; if you take it out of draft state (I'd rather not do that for you), I can merge it.  If you're waiting for a successful test run on Windows, let me know, and I'll add Windows to the GitHub Actions matrix, and then you can rebase to get a CI run on Windows.

As for property-manager -> humanfriendly -> pyreadline causing problems, I believe I can replace it with `functools.cached_property` (or [`cached-property`](https://pypi.org/project/cached-property/) before Python 3.8).

**Comment by domdfcoding** [comment]
I think this is ready to go.

I have opened #22 to discuss Windows tests further.

**Pull request merged**
